### ISSUE TITLE
Which commit supports webgl1?

### ISSUE THREAD

**Issue by bergwerf** [ChronosTeam/ChronosGL#111]
I want to build some simple interactive graphics in Dart and this library is the only maintained WebGL wrapper. However WebGL2 is a bit too modern for me (I want to support more browsers), and I don't need it (I'll just be rendering some spheres). Can I use a previous version of ChronosGL that supports webgl1?

**Comment by robertmuth** [comment]
you could go back in the commit history to before the switch to Webgl2. The drawbacks are:
* you also need to fix the dart 2.0 issues
* there are more bugs
* the examples/documentation are fewer/worse

Currently the only downside of using WebGL2 is that Safari is not supporting it unless you activate 
an experimental feature. This causes issues on i-phones where there are no real alternative browsers.
 
https://caniuse.com/#feat=webgl2

**Comment by bergwerf** [comment]
Good points. However currently Edge also doesn't support webgl2 and I would
definitely like to support safari users on iPads. I'll look into switching
to typescript or writing something simple myself.
