### ISSUE TITLE
IE11 instancing

### ISSUE THREAD

**Issue by unicomp21** [ChronosTeam/ChronosGL#18]
Given it will probably be some time before we get a fix on IE11 instancing.  Would it be worthwhile to wrap the javascript webgl instancing w/ a Dart class?

This pure javascript example works on all browsers.

http://blog.tojicode.com/2013/07/webgl-instancing-with.html

**Comment by muth02446** [comment]
I do not have easy access to ie11 - is this still an issue?

**Comment by muth02446** [comment]
ping

**Comment by muth02446** [comment]
no recent update - closing
