### ISSUE TITLE
Switch to WebGL2

### ISSUE THREAD

**Issue by robertmuth** [ChronosTeam/ChronosGL#69]
This more of an announcement than a "bug",

ChronosGL will switch to WebGL2 as soon as the dart sdk supports it - likely before the end
of Q2 2017.

The webgl2 branch already provides a preview of what is going to change.

**Comment by unicomp21** [comment]
Awesome!

Now if we could just get pbrt like Babylon.js

**Comment by robertmuth** [comment]
The WebGL2 branch is now "master".

Note that you need the DEV CHANNEL SDK and Dartium for this to work

Dartium also needs to be run with --enable-unsafe-es3-a pis
