### ISSUE TITLE
Text on geometry

### ISSUE THREAD

**Issue by jonboj** [ChronosTeam/ChronosGL#77]
I try get text on a geometry, looking into `threeDart` this is done by generation of Shapes for the te string with `FontUtils.generateShapes`.

https://github.com/threeDart/three.dart/blob/master/lib/extras/geometries/text_geometry.dart#L10

---
Next step is try to do some equivalent in ChronosGL. I consider a modification of `FontUtils.generateShapes` to in ChronosGL generate a `MeshData`.

Question does ChronoGL already provide text on geometry? Or suggestions to alternatives to the design above.

**Comment by rhulha** [comment]
One easy way to get text on geometry is to use a HTML5 Canvas as a texture and write text on the Canvas using fillText: https://www.w3schools.com/graphics/canvas_text.asp

There should be an example on how to use a Canvas as a Texture in the ChronosGL examples.

**Comment by robertmuth** [comment]
If you need three dimensional letters you can try to port a full blown external library as you describe or you could do this:
1) extract a two dimensional description of the letter in form of one or more polygons, e.g. the letter would
   basically be two concentric circles.
2) extrude the polygons 
3) add caps to each side
There is already rudimentary support for 2) and 3) in ChronosGL, see
  https://github.com/ChronosTeam/ChronosGL/tree/master/lib/src/polygon
I would be happy to add necessary functionality if needed.

**Comment by jonboj** [comment]
Managed to get text on different geometries with a canvas as suggested above by rhulha. Close issue.
