### ISSUE TITLE
version handling - at release consider git tag with version

### ISSUE THREAD

**Issue by jonboj** [ChronosTeam/ChronosGL#78]
Possibility for confusion with the versions.

pubspec.yaml version: 3.1.0
latest tag in git : 1.2.1

Of course one could follow the commit history of pubspec.yaml and extract the corresponding commit, but more standard and transparent if the repository is tagged with the version at release.

On pub.dartlang.org version 2.1.2. Great it makes sense not to publish all versions from git, but then maybe the tagging in git of releases is more important, since it emphasis that only a subset of releases from git are published at pub.

**Comment by robertmuth** [comment]
I am not git power user and was not even aware to the git tag.
Are the any write-up on best practices?
My gut reaction would to just drop the git tag if that is possible since the version in
pubspec.yaml is authoritative.

BTW: I pushed a new package  to https://pub.dartlang.org/packages/chronosgl
Make sure you use that or tip of tree since there were a ton of breaking changes recently.

**Comment by jonboj** [comment]
Great I understand, no problem. Previous to git I worked with other CM tools (Clear Case). Git is very powerful and now more less de facto standard. That said even with good knowledge of git, the user interface could be misleading and sometimes even obscure.

At the moment I don't find like a best practice of version handling on github. But for the tagging I can refer to the dart-sdk project https://github.com/dart-lang/sdk/tags A purpose of the tagging is to create an one to one correspondence between source and build product. Especially useful for bug handling. Just for illustration, lets say a bug was introduced when upgrading from 2.1.0 to 2.1.2, this could actually be in the app build on top of the lib using the api in an unintended way. The most straight way ahead to search for the origin of the bug is to diff the source between the two versions, here the tagging comes into play with finding the commits in the source tree.

To tag a repo is a simple operation (all the writing above is just for giving a background).

**Comment by robertmuth** [comment]
I'll start tagging from now on
