### ISSUE TITLE
Does not work on Dartium ( which is Chrome r50 )

### ISSUE THREAD

**Issue by sandrobilbeisi** [ChronosTeam/ChronosGL#80]
Currently version only runs on Chrome r56 or above ( I've tested it 100% working with Chrome r59)

It does not work on Dartium ( which is Chrome r50 ) not even by activating the WebGL2 flag ...

**Comment by jonboj** [comment]
Confirm - same in my environment Ubuntu 17.06 with intel grapics processor. Anyhow so fare works with ok with the ddc dev environment.

**Comment by robertmuth** [comment]
Does your dartium 50 show webgl2 compliance when navigating to:
http://webglreport.com/?v=2

**Comment by sandrobilbeisi** [comment]
no, it does NOT show compliance

**Comment by robertmuth** [comment]
As of version 3.X chronosgl is WebGL2 *only* so this explains the problem:
Chrome enabled WebGL2 in r56 by default. Older versions including Dartium 50 needs some 
config changes.
The example index.html page has some hints:
https://github.com/ChronosTeam/ChronosGL/blob/master/example/index.html

try (in chrome://flags) 
enable-unsafe-es3-apis
All examples should work with a properly configured Dartium 50.

**Comment by jonboj** [comment]
Dartium 50, Ubuntu 17.04. Still with flag enabled, the webglreport shows not supported. With ddc and latest Chrome (59) working no necessity for me with Dartium (Dart team at the moment swifts from Dartium to ddc as main/recommended dev env).

**Comment by robertmuth** [comment]
This definitely works for me.
Maybe chrome does not have your GPU whitelisted
The setting is "Override software rendering list" I believe.
