### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by unicomp21** [ChronosTeam/ChronosGL#95]
Not sure why this is happening.  Getting it on both windows and linux, in webstorm.

Working dir: C:\Users\unico\repo\ChronosGL
"C:\Program Files\Dart\dart-sdk\bin\pub.bat" get
Resolving dependencies...
Package build_runner has no versions that match >=0.8.8 <0.9.0 derived from:
- chronosgl depends on version ^0.8.8
Process finished with exit code 1

**Comment by robertmuth** [comment]
you need to use the dev channel SDK now. For me this looks like:

dart --version
Dart VM version: 2.0.0-dev.59.0 (Unknown timestamp) on "linux_x64"

Note: dartium is no longer used/supported in this SDK.

Also, things are a bit in a messy state after dart switched to a new build system "webdev"

I just pushed a few more commits try running:

make get
followed by 

make examples
or
make serve

**Comment by robertmuth** [comment]
is this working for you now?

**Comment by unicomp21** [comment]
Thanks Robert!
